using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class QuestSystemSaveTest : MonoBehaviour
{
	[SerializeField] private Quest quest;
	[SerializeField] private Category category;
	[SerializeField] private TaskTarget target;

	private void Start()
	{
		var questSystem = QuestSystem.Instance;

		if (questSystem.ActiveQuests.Count == 0)
		{
			Debug.Log("Resister");
			var newQuest = questSystem.Register(quest);
		}
		else
		{
			questSystem.onQuestCompleted += (quest) =>
			{
				Debug.Log("Complete");
				PlayerPrefs.DeleteAll();
				PlayerPrefs.Save();
			};
		}
	}


	private void Update()
	{
		if (Input.GetKeyDown(KeyCode.Q))
			QuestSystem.Instance.ReceiveReport(category, target, 1);
	}
}
